### ISSUE TITLE
Colocar um comentário neste issue com a URL para acesso à aplicação.

### ISSUE THREAD

**Issue by tmsasaki** [Montini/ppads-projeto-05J#10]

**Comment by Montini** [comment]
Projeto hospedado na S3 Amazon.

http://mackbussola.s3-website-sa-east-1.amazonaws.com/

**Comment by Montini** [comment]
Projeto migrado para plataforma Elastic Beanstalk da AWS.

http://default-environment.8mdzq2gzef.sa-east-1.elasticbeanstalk.com/index.html
