### ISSUE TITLE
Elaborar detalhamento de componentes.

### ISSUE THREAD

**Issue by tmsasaki** [Montini/ppads-projeto-05J#11]
1. Execute o Git Bash.

2. Caso ainda não tenha feito o clone, execute (lembre-se de substituir USUARIO):

    git clone https://github.com/USUARIO/ppads-projeto-05J

3. Acesse o diretório de trabalho:

    cd ppads-projeto-05J

4. Adicione o repositório do professor como upstream:

    git remote add upstream https://github.com/tmsasaki/ppads-projeto-05J

5. Atualize a sua cópia de trabalho:

    git fetch upstream
    git checkout master
    git rebase upstream/master

6. Atualize o seu repositório:

    git push –f origin master

7. Atualize o documento que está na pasta docs/4-componentes.

**Comment by LeticiaFSouza** [comment]
A tarefa foi entregue e avaliada.
