### ISSUE TITLE
Haverá somente a opção de busca pelo nome da faculdade, ou também será possível buscar pelo número/nome do prédio, nomes de salas/auditórios?

### ISSUE THREAD

**Issue by tmsasaki** [Montini/ppads-projeto-05J#4]

**Comment by Montini** [comment]
A busca será disponibilizada através de um diretório em formato de lista, divido em duas categorias: Faculdades e Restaurantes.
Essa lista disponibilizará o nome da Faculdade e do Restaurante, com informações do tipo: Descrição, telefone e e-mail.
