### ISSUE TITLE
Elaborar documento de arquitetura.

### ISSUE THREAD

**Issue by tmsasaki** [Montini/ppads-projeto-05J#9]
1) Execute o Git Bash.
2) Caso ainda não tenha feito o clone, execute:

    git clone https://github.com/seuLoginGitHub/ppads-projeto-05J

3) Acesse o diretório de trabalho:

    cd ppads-projeto-05J

4) Adicione o repositório do professor como upstream:

    git remote add upstream https://github.com/tmsasaki/ppads-projeto-05J

5) Atualize a sua cópia de trabalho:

    git fetch upstream
    git checkout master
    git rebase upstream/master

6) Atualize o seu repositório:

    git push –f origin master

7) Atualize o documento que está na pasta docs/3-arquitetura.

**Comment by Montini** [comment]
Atividade concluida.
